### ISSUE TITLE
Cannot read property 'build' of undefined

### ISSUE THREAD

**Issue by DenisVuyka** [nitayneeman/made-with-love#3]
Running `ng add angular-made-with-love` causes an error:

```
Installed packages for tooling via npm.
    ✅️ Added "@angular/elements" into dependencies
    ✅️ Added "@webcomponents/custom-elements" into dependencies
    ✅️ Added "angular-made-with-love" into dependencies
    🔍 Installing packages...
Cannot read property 'build' of undefined
```

Used with the Angular 6:

```
Angular CLI: 6.2.1
Node: 10.7.0
OS: darwin x64
Angular: 6.1.7
```

**Comment by nitayneeman** [comment]
It turns out that `architect` was renamed to `targets` in the `angular.json` schema:
https://github.com/angular/angular-cli/commit/dcdb937e41ec5955d7d0503ffa131134fcc801b1

This issue is fixed in v2.0.3.
